# Generated by Django 3.2.9 on 2023-09-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('subnet_mask', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
